[tool.poetry]
name = "dejavu"
version = "0.1.0"
description = ""
authors = ["Caswall Engelsman <mail@cengelsman.com>"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
